# Based on https://github.com/rtfeldman/elm-spa-example
sudo: false

cache:
  directories:
    - tests/elm-stuff/build-artifacts

install:
  - npm install -g elm@0.19.0-bugfix2 elm-test elm-format

script:
  - elm-format --validate .
  - elm-test
